### PR TITLE
fix(resolve-rc): look for babel in package.json

### PR DESCRIPTION
**Pull request by mastilver**
**Please Read the [CONTRIBUTING Guidelines](https://github.com/babel/babel-loader/blob/master/CONTRIBUTING.md)**
*In particular the portion on Commit Message Formatting*

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the following...

* Impact:
* Migration path for existing applications:
* Github Issue(s) this is regarding:

**Other information**:

### CODE REVIEW

**Comment by danez** [comment]
Awesome thank you very much. 
By looking at the code I noticed that `babelrc.js` is not supported (which is coming with babel 7).
Instead of further modifying this code, what do you think about using https://github.com/tleunen/find-babel-config? It already supports the new file. And would make the babel-loader code more easy by outsourcing this part.

**Comment by evilebottnawi** [comment]
@danez 
> We would still need to do the caching.
Now it is not work as expected. Step:
1. Run `webpack` in watch mode.
2. Just edit config file - rebuilding process not started.

How to solve:
1. Use `this.addDependency` for configuration file (`.babelrc` and etc), how it is do `postcss-loader` https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L93

**Comment by mastilver** [comment]
@evilebottnawi I think what @danez was saying is for performance sake `find-babel-config` should have caching

What you mention is a different issue and from my point of view is not an issue
`webpack` only watch "code" files not config files, if you update your `.babelrc` you are required to restart `webpack`

**Comment by evilebottnawi** [comment]
@mastilver @danez This is fundamentally wrong and breaks the logic of watching and caching.
Each loader using config files should be add their to watch graph.

From webpack channel as say @sokra:
```shell
sokra [4:54 PM] 
configuration files -> loaders should add these files to their dependencies (with `this.addDependency`). dependencies' mtimes are stored by the cache-loader
```

Also it is break loader before, example `cache-loader`, actually loaders using before `babel-loader` a lot more and many of their also can improve own cache. All this makes the cache invalid and is a wrong look at watch graph.

**Comment by mastilver** [comment]
@evilebottnawi I take back what I said but can you open an issue about it, this PR is not related to your issue

**Comment by danez** [comment]
Thanks this was merged with d8b73c04fc0b984a3c80d9b918f45ddc95fe9893

**Comment by mastilver** [comment]
@danez Thank you for taking care of it :) , don't have much time atm

**Comment by ismay** [comment]
@danez This hasn't yet been released on npm right?

**Pull request closed without merging**
