### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by sairion**
Some people might want much faster, newer Babel on first installation maybe?

### CODE REVIEW

**Comment by arkist** [comment]
:+1:

**Comment by sebmck** [comment]
This will already happen because it's a `^` range...

**Comment by Couto** [comment]
Yes I know, but I'm currently closing the PRs so it was kinda of an automatic reaction of mine! :)

**Comment by arkist** [comment]
@sebmck oh, you're right :0

**Comment by sairion** [comment]
Oops, I just found out I was confusing caret range. Sorry, and thanks!

**Pull request merged**
