### PR TITLE
Upgraded to Babel 6

### PR DESCRIPTION
**Pull request by mlegenhausen**
As you requested a pull request in #123. Here it is ;)

Main changes were to add `presets: ['es2015']` to all the loader calls. I removed your `experimental.js` cause the contained array comprehension is not supported any more (no plugin available) and replaced it by `basics.js`.

### CODE REVIEW

**Comment by shinnn** [comment]
I'd like to confirm this update passes the test. https://github.com/babel/babel-loader/pull/124

**Comment by Couto** [comment]
I've merged this to the branch develop, give it a try ;)
I'll merge it to master later on, if everything is nice!

**Comment by chicoxyzzy** [comment]
is everything nice? :)

**Comment by Couto** [comment]
Everything was nice indeed! Thanks a lot! :+1:

**Comment by mlegenhausen** [comment]
You're welcome :)

**Pull request merged**
