### PR TITLE
[5.x branch only] Add support for webpack 1 & 2

### PR DESCRIPTION
**Pull request by nemtsov**
Add support for webpack 2 for branch that supports babel 5

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks 😀

**Comment by hzoo** [comment]
@Couto can you make the 5.4.1 release or add me on npm (hzoo)?

**Comment by Couto** [comment]
@hzoo You should have access as a contributor now.
Thanks for all your hard work btw! You've been awesome in maintaining this! :)

**Comment by hzoo** [comment]
haha thanks! I actually unwatched for a while though 😛

**Comment by hzoo** [comment]
@Couto just wondering if you'll be able to help maintain moving forward (totally understandable, everyone gets busy, life, etc) - I asked some others to help https://github.com/babel/babel-loader/issues/276.

**Comment by Couto** [comment]
@hzoo I probably won't have the time to help you guys, between family, work and some future projects, it's really hard to keep up with everything.

I've just saw the announcement in #276. If you guys need anything from me (either questions, or publishing permissions), feel free to shout, and I'll help as soon as I can.

Apart from that, all I ask is the privilege to make any change that I might need (hardly really, since  babel-loader has been working fine for my needs), but If I do any change, I promise to keep your standards and work flow and I'll try not to be disruptive. Is that ok with you guys? :)

**Comment by d3viant0ne** [comment]
@Couto - It would probably be a good idea we could schedule a quick ~10 chat with myself & @danez on Slack.

We certainly don't have any plans to make major sweeping changes as `babel-loader` is in a pretty good spot. None the less, it will probably make the transition go a bit smoother if everyone is on the same page. In particular, understanding what if anything you had envisioned for the next major and I do have a few questions related to the 5.x / develop branch.

As far as the next Major goes which is certainly down the road a ways, we will ensure you are kept in the loop as far as planning goes ( all of which will be public ) and of course incorporate any use cases you need covered.

Outside of that it's all going to be `semver Minor / Patch`,  a few administrative changes and some project management sugar.  I promise we will take good care of your baby :)

**Comment by Couto** [comment]
@d3viant0ne Hey! Sure, I'm going to request an invitation to babel's slack is that ok? :)

**Comment by hzoo** [comment]
You can just join with the chat link on the homepage - you can just do it in discussion/development or we can make a webpack room

**Comment by d3viant0ne** [comment]
It's all been taken care of, good talk & everyone is on the same page. Thanks :)

**Pull request merged**
