### PR TITLE
Move @ava/babel to devDependencies

### PR DESCRIPTION
**Pull request by jvasseur**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other: dependencies fix.

**What is the current behavior?** (You can also link to an open issue here)

When installing babel-loader, `@ava/babel` is installed with it while it's not used

**What is the new behavior?**

It's not installed anymore.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

**Other information**:

Adding it to `dependencies` instead of `devDependencies` was probably a mistake, this fixes it.

### CODE REVIEW

**Review by JLHwung — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Whoops thanks!

**Comment by pieh** [comment]
Any chance we could get patch release with this change? 

On top of installing it unnecessarily, it also cause some problems due to `engines.node` - excerpt from `yarn` installation:

```
error @ava/babel@1.0.1: The engine "node" is incompatible with this module. Expected version ">=10.18.0 <11 || >=12.14.0 <13 || >=13.5.0". Got "10.16.0"
error Found incompatible module.
```

(`@ava/babel@1.0.1`'s `engines.node` is more strict that of `babel-loader` itself )

**Comment by nicolo-ribaudo** [comment]
Yup, I will release later today.

**Comment by nicolo-ribaudo** [comment]
Published as 8.2.1

**Pull request merged**
