### PR TITLE
Make babelrc configurable

### LINKED ISSUE #107: .babelrc location not configurable
Is it true that the babelrc location can not be specified in the loader options? (I guess so because of `delete options.babelrc;` in `index.js`). Why is that the case?

### PR DESCRIPTION
**Pull request by MaartenVerbaarschot**
This fixes #107

### CODE REVIEW

**Comment by thealjey** [comment]
this would've beed very useful if it wasn't for [#1886](https://github.com/babel/babel/issues/1886#issuecomment-153729262) (see my comment at the bottom)

**Comment by Couto** [comment]
Deleting the option won't affect much since babel is not expecting any `babelrc` option itself: https://babeljs.io/docs/usage/options/

So I have to ask, are you trying to read options from babelrc or just trying to bust the internal cache ?

**Comment by Couto** [comment]
I've read the linked discussion.
As far as I can tell from the docs, there's no babelrc option, still it seems that nothing breaks by allowing the option, so might as well not forbid it.

It's currently in the master and develop branch, give it a try, I should make a release tomorrow

**Comment by thealjey** [comment]
@Couto https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/config.js#L131

**Comment by Couto** [comment]
@thealjey lol someone should update the website :dancer:

**Comment by thealjey** [comment]
@Couto
the problem is that it is currently an on/off switch tells babel whether to search for **.babelrc** or not
there's currently no way to specify a specific file to use

For example, `ESLint` has a **--config** flag (**.eslintrc** is just a convenient default), `JSDoc` has a **--configure** flag, `scss-lint` has a **--config** flag for specifying a configuration file to use.

This is basically the reason why to this day I was not able to use **.babelrc** on my project (but I really want to for obvious reasons).
For the API functions it's not that big a deal, because it's easy to pass a config object to them.
As to the CLI it's not as easy, and not possible in some cases.

I would also just love it if the configuration could be written in the YAML format (just a personal preference).

**Comment by SamanthaAdrichem** [comment]
If this still works, could you add it to the documentation in readme.md?

**Pull request merged**
