### PR TITLE
Use md4 instead of sha1 for filename hashes

### PR DESCRIPTION
**Pull request by lencioni**
We don't need the cryptographic strength of SHA-1 for this purpose, so
we may as well use a faster hashing algorithm.

While I was at it, I also sapped out the use of hash.end + hash.read
combo for the faster and more conventional hash.update + hash.digest. In
my local testing, this also seems to offer a nice speed boost.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Uses SHA-1 for cache filename hash.

**What is the new behavior?**

Uses MD4 for cache filename hash.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

**Other information**:

I wrote this PR against the 7.x branch in hopes that we could get it into a 7.x release. If you think this is a good approach, I am happy to open a similar PR against master.

### CODE REVIEW

**Comment by existentialism** [comment]
We should land this change in `master` too?

**Comment by xtuc** [comment]
Yes that's a good idea.

**Comment by hzoo** [comment]
And we can release this as a patch?

**Comment by hzoo** [comment]
https://github.com/babel/babel-loader/releases/tag/v7.1.5

**Pull request merged**
