### PR TITLE
support sync compilation

### PR DESCRIPTION
**Pull request by camshaft**
this is needed for using the [enhanced-require](https://www.npmjs.com/package/enhanced-require)

### CODE REVIEW

**Comment by sebmck** [comment]
Why did you change the style of all the code?

On Thursday, 7 May 2015, Cameron Bytheway <notifications@github.com> wrote:

> this is needed for using the enhanced-require
> <https://www.npmjs.com/package/enhanced-require>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/babel/babel-loader/pull/60
> Commit Summary
>
>    - support sync compilation
>
> File Changes
>
>    - *M* index.js
>    <https://github.com/babel/babel-loader/pull/60/files#diff-0> (249)
>
> Patch Links:
>
>    - https://github.com/babel/babel-loader/pull/60.patch
>    - https://github.com/babel/babel-loader/pull/60.diff
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel-loader/pull/60>.
>


-- 
Sebastian McKenzie

**Comment by camshaft** [comment]
are you referring to the whitespace or the structure of the functions?

**Comment by sebmck** [comment]
The changing whitespace, splitting up of declarations, the general "style" of the code.

**Comment by camshaft** [comment]
i can change it back. the way it was before was hard to read for me.

**Comment by camshaft** [comment]
should be fixed. let me know if i need to make any other changes.

**Comment by Couto** [comment]
I'm reading the code to merge this with the [develop](https://github.com/babel/babel-loader/tree/develop).
Since the code in the develop branch is quite different from the master, do you wanna take a stab at redoing this PR to the develop branch?

If not, which is ok, the whole point on making this work with enhaced-require is to make the code run synchronously if `this.async()` returns a falsy value is that right?

**Comment by camshaft** [comment]
That's correct. I can look at the develop branch and let you know.

**Comment by danez** [comment]
Closing, as it seems to be resolved by #79

**Pull request closed without merging**
