### PR TITLE
Permit webpack@2 betas

### PR DESCRIPTION
**Pull request by pyrotechnick**
Thank you to @Hatlen & @Couto for schooling me in SemVer

### CODE REVIEW

**Comment by Couto** [comment]
Ahaha you could just push a new commit with the change, but this also works. ;)
I don't know much of semver so it was also some trial and error on my part.

I'll merge this later tonight.

**Comment by johanneslumpe** [comment]
@Couto Do you think this will get merged today and a new version can be published? :)

**Comment by RoberMac** [comment]
@Couto @johanneslumpe seem beta version release too frequently before stable release, why not just manually edit package.json locally ?

**Comment by johanneslumpe** [comment]
@RoberMac I did do that ;) But that doesn't help when you want to push something to production where `npm i` occurs on the server.

**Comment by pyrotechnick** [comment]
@johanneslumpe 

Just use `pyrotechnick/babel-loader#c7d6359ac7ff202a0d82e7a64f87b147d8ec4f9b`

i.e.

```js
{
  "name": "my-awesome-module",
  "dependencies": {
    "babel-loader": "pyrotechnick/babel-loader#c7d6359ac7ff202a0d82e7a64f87b147d8ec4f9b"
  }
}
```

See https://docs.npmjs.com/files/package.json#github-urls for more info ^w^

**Comment by johanneslumpe** [comment]
@pyrotechnick That's a solution yes, but I still think this should be fixed on the project itself, without having to resort to custom github urls/forks. :)

**Comment by pyrotechnick** [comment]
For what it's worth @Couto merged and released my first PR within an hour.

Bare in mind we are using a tree of software explicitly marked as pre-release so it is vital to be patient and resourceful when awaiting releases of changes as trivial as these.

**Comment by johanneslumpe** [comment]
@pyrotechnick I'm not impatient, just asking. I don't want to push anybody here to hurry a release it is isn't feasible. I've already resorted to a different solution.

**Comment by RoberMac** [comment]
seem `^2.1.0-beta` will match [all](https://github.com/webpack/webpack/issues/2004) [betas](https://github.com/webpack/webpack/commit/52822286a347bf525eeab7f035341fc25e857914), @Couto why not merge this now ?

**Comment by Couto** [comment]
Everyone can find this patch on npm with the version 6.2.4. Thanks everyone.

@RoberMac my delay was mostly because of my lack of time for merging this. Sorry :\

**Comment by johanneslumpe** [comment]
@Couto no need to be sorry for anything :)

**Pull request merged**
