### PR TITLE
Add path-is-absolute dependency

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
Fixes #80

**Comment by jonprins** [comment]
:+1:

**Comment by thejameskyle** [comment]
Merging

See: https://github.com/babel/babel-loader/commit/5db74225bfa778635c19bd5de1b10b4715b13e1d#diff-5e90e7d094b642aa40f125760e67eb4fR17

**Comment by thejameskyle** [comment]
@Couto @sebmck Can one of you guys make a patch release?

**Pull request merged**
