### PR TITLE
Change 6t05 to babel in the package.json description

### PR DESCRIPTION
**Pull request by hawkrives**
Should I also add the `babel` keyword?

### CODE REVIEW

**Comment by Couto** [comment]
Yes. I believe that adding the keyword babel would improve search results. 
Would you mind adding it to the PR?

**Comment by hawkrives** [comment]
Done! 

I think that we should probably leave the 6to5 keyword, at least for now, so that it still shows up for people searching for 6to5.

**Comment by Couto** [comment]
I agree.
Thanks for the PR :)

**Comment by hawkrives** [comment]
No prob. Thanks for making things!

**Pull request merged**
