### PR TITLE
updated webpack version and also modified babel-loader version

### PR DESCRIPTION
**Pull request by saranshkataria**
updated babel-loader version since beta is no longer a version, there are beta.1 and beta.2 versions of babel-loader now. Also webpack 4 is the latest version, so bumped that up as well

**Please Read the [CONTRIBUTING Guidelines](https://github.com/babel/babel-loader/blob/master/CONTRIBUTING.md)**
*In particular the portion on Commit Message Formatting*

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: Documentation update

**Does this PR introduce a breaking change?**
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Hello @saranshkataria,
I think you can add a `--save-dev` at the end of each line.

 ```bash
npm install "babel-loader@^8.0.0-beta.2" @babel/core @babel/preset-env webpack --save-dev
 ```
 ```

**Comment by saranshkataria** [comment]
@guillaumevincent I was thinking of adding that and did some research of why it had not been put in place before. Since dev dependencies are not downloaded in a production environment and https://github.com/webpack/webpack/issues/520 this states to add them in dependencies to ensure builds running when webpack is called in production. So I had not added the save-dev flag

**Comment by danez** [comment]
The `@^8.0.0-beta.2` is not necessary and should stay as `@^8.0.0-beta` which always installs the latest beta version.

**Comment by saranshkataria** [comment]
For some reason, it was not working on my machine yesterday. Hence had created this PR.
Worked when I tried it today. Not sure what the issue was

**Pull request closed without merging**
