### PR TITLE
Update package.json

### LINKED ISSUE #100: babel-core dependencies
`package.json` has specified 3 versions of dependencies for `babel-core`; this seems to be redundant and calls for a clean-up.

### PR DESCRIPTION
**Pull request by gsklee**
Fix #100

Remove redundant dependency declarations for `babel-core`

### CODE REVIEW

**Comment by joneslee85** [comment]
please close

**Comment by gsklee** [comment]
@joneslee85 It's currently in both `peerDependencies` and `devDependencies ` and I don't understand why.

**Comment by shinnn** [comment]
This is why. https://github.com/npm/npm/issues/6565

**Comment by gsklee** [comment]
@shinnn Then why not just listed it as a `dependencies`?

**Comment by mischkl** [comment]
@gsklee 
> Then why not just listed it as a dependencies?

because then it would be forcing a specific version of babel-core on the users of this package. By having it as a peerDependency with the version "*" it can support any version of babel-core the user has installed. But for testing purposes a specific version is specified in devDependencies.

**Pull request closed without merging**
