### PR TITLE
migrate to c8

### PR DESCRIPTION
**Pull request by JLHwung**
**Please Read the [CONTRIBUTING Guidelines](https://github.com/babel/babel-loader/blob/main/CONTRIBUTING.md)**
*In particular the portion on Commit Message Formatting*

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes: migrate to `c8`
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

**Other information**: Migrate to `c8`, leveraging the v8 builtin coverage tools.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Can we setup a CI check that shows the current coverage, with codecov or something similar?

**Comment by JLHwung** [comment]
Here is the current coverage report: https://app.codecov.io/gh/babel/babel-loader

Can you install the codecov GitHub application to this repo? So the coverage should show up in checks.

**Comment by nicolo-ribaudo** [comment]
I see it as already enabled 🤔 I'll try to understand why it's not working

image

image

**Comment by nicolo-ribaudo** [comment]
Oh, it also stopped reporting the coverage in the babel/babel repo since July 5th

**Comment by JLHwung** [comment]
The coverage report now looks good to me: https://app.codecov.io/github/babel/babel-loader/commit/3ed721a5c2c0af04dbac02d3f40ce20adcba3ee5/tree/src

I have no idea why the codecov check is missing. BTW the check in Babel repo is also missing:

image

Here is the last four checks from https://github.com/babel/babel/pull/15763

**Review by liuxingbaoyu — APPROVED** [review]

**Comment by nicolo-ribaudo** [comment]
Codecov is back :)

**Pull request merged**
