### PR TITLE
Use md5 hashing for OpenSSL 3

### PR DESCRIPTION
**Pull request by pathmapper**
**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

https://github.com/babel/babel-loader/issues/923

**What is the new behavior?**

Check `process.versions.openssl` instead of `process.versions.node`.

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JLHwung — COMMENTED** [review]
I think it'd better do a top level feature detection. We can try create to create an `md4` hasher and switch to `md5` if it throws.

OpenSSL 1.1.1 can disable `md4` via `--no-md4` building options. [[1]](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/INSTALL)

OpenSSL 3.0 can enable `md4` via legacy provider config option. [[2]](https://www.openssl.org/docs/man3.0/man7/OSSL_PROVIDER-legacy.html)

**Comment by pathmapper** [comment]
@JLHwung is https://github.com/babel/babel-loader/pull/924/commits/ba921159211569c040b011336aba3b3bcfeec363 what you are thinking about?

**Comment by pathmapper** [comment]
> move the feature detection to the top level

done

**Review by JLHwung — APPROVED** [review]

**Comment by pathmapper** [comment]
Any chance to get this merged?

**Comment by sirin2639** [comment]
Has anyone tested this change on RH Linux?  RH Linux enables FIPS and md5 isn't allowed on a FIPS compliant system.

**Comment by sonnyp** [comment]
babel-loader is currently unusable on Fedora 36. The beta is due to release this month.

I added some links in https://github.com/babel/babel-loader/pull/934 about webpack approach in case of interest.

**Review by JLHwung — APPROVED** [review]

**Review by nicolo-ribaudo — APPROVED** [review]

**Pull request merged**
